title: Sungsoo Kim
position: Researcher in Theoretical High-Energy Physics
affiliation: KIAS Amplitudes Team
email: sooo4017 (at) snu.ac.kr

keywords: scattering amplitudes, particle physics, mathematical physics, classical eikonal, magnus expansion, hep-th
description: Personal academic homepage of Sungsoo Kim
canonical: https://kimbd1222.github.io/sungsoo-kim-133/

google_scholar: https://scholar.google.com/citations?user=qQhCxrcAAAAJ&hl=en
github_link: https://github.com/Kimbd1222
inspirehep: https://inspirehep.net/authors/2875140
cv_link: assets/files/CV.pdf

avatar: ./assets/img/profile.png
#favicon: ./assets/img/avatar.png
#favicon_dark: ./assets/img/avatar.png

enable_footnote: true
auto_dark_mode: true
font: "Sans Serif"